name: Build and push container images

on:
  push:
    branches:
      - 'main'
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_DESCRIPTION: ${{ github.repository }} container for use with Mythic
  IMAGE_SOURCE: ${{ github.server_url }}/${{ github.repository }}
  IMAGE_LICENSE: BSD-3-Clause
  VERSION: ${{ github.ref_name }}
  RELEASE_BRANCH: main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Lowercase the image name
        run: echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: C2_Profiles/reverse_tcp
          file: C2_Profiles/reverse_tcp/.docker/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          push: ${{ github.ref_type == 'tag' }}
          labels: |
            org.opencontainers.image.source=${{ env.IMAGE_SOURCE }}
            org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}
            org.opencontainers.image.licenses=${{ env.IMAGE_LICENSE }}
          platforms: linux/amd64

  update_files:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref_type == 'tag' }}
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Lowercase the image name
        run: echo "IMAGE_NAME=${IMAGE_NAME,,}" >> ${GITHUB_ENV}

      - name: Update Dockerfile to reference the new release tag
        working-directory: C2_Profiles/reverse_tcp
        run: |
          sed -i "s|^FROM ghcr\.io.*$|FROM ${REGISTRY}/${IMAGE_NAME}:${VERSION}|" Dockerfile

      - name: Update config.json remote_images version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: config.json
          field: remote_images.reverse_tcp
          value: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

      - name: Commit and push updated files
        uses: EndBug/add-and-commit@v9
        with:
          add: "['C2_Profiles/reverse_tcp/Dockerfile', 'config.json']"
          default_author: github_actions
          committer_email: github-actions[bot]@users.noreply.github.com
          message: "Bump Dockerfile tag to match release '${{ env.VERSION }}'"
          tag: '${{ env.VERSION }} --force'
          tag_push: '--force'
          push: origin HEAD:${{ env.RELEASE_BRANCH }} --set-upstream
          pathspec_error_handling: exitImmediately
